name: thels_kitchen
description: "A recipe app made with love for Thel."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.3.2
  just_audio: ^0.10.6
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audios/
    - assets/images/
